config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
	resources :posts

	root 'posts#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
	validates :subtitle, presence: true, length: { minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def show
		@post = Post.find(params[:id])
		@posts = Post.order("created_at desc").limit(4).offset(1)
	end

	private
		def post_params
			params.require(:post).permit(:title, :subtitle, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Dev Blog - Jason</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'freelancer', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119870194-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119870194-1');
    </script>


  </head>

  <body>

    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    
  </body>
</html>

app/views/posts/index.html.erb
<%= react_component "Posts", {posts: @posts}%>

<!-- Portfolio Grid Section -->
<!--
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 mx-auto">
                <% @posts.each do |post| %>
                    <div class="post-preview">
                    <%= link_to post_path(post), nil, {:style=>'text-decoration: none;', :class => "css_class"} do %>
                        <h2 class="post-title">
                            <%= post.title %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= post.subtitle %>
                        </h3>
                        <p> Posted on September 10, 2017</p>
                    <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>
-->

app/views/posts/show.html.erb
    <script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://gojasonyang-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
    </script>

    <script type="text/javascript" src="//cdn.chitika.net/getads.js" async></script>

    <script type="text/javascript">
  ( function() {
    if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
    var unit = {"calltype":"async[2]","publisher":"dci05049","width":160,"height":600,"sid":"Chitika Default"};
    var placement_id = window.CHITIKA.units.length;
    window.CHITIKA.units.push(unit);
    
    var unit = {"calltype":"async[2]","publisher":"dci05049","width":550,"height":250,"sid":"Chitika Default"};
    var placement_id = window.CHITIKA.units.length;
    window.CHITIKA.units.push(unit);
    
    var unit = {"calltype":"async[2]","publisher":"dci05049","width":550,"height":250,"sid":"Chitika Default"};
    var placement_id = window.CHITIKA.units.length;
    window.CHITIKA.units.push(unit);
    
}());
</script>

<!-- Page Content -->
<div class="container post-container">

    <article>
        <div class="container">
            <div style="text-align: center; margin-top: 20px; margin-bottom: 50px;" class="post-heading">
                    <h1> <%= @post.title %></h1>
                    <h2 class="subheading"><%= @post.subtitle %></h2>
                </div>
            <div class="row">
                <div id="chitikaAdBlock-0"></div>
                </div>

                <div class="col-lg-9 col-md-9 offset-md-2">
                <!-- /.row -->
                    <%= @post.body.html_safe %>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-9 offset-md-2">
        <div id="disqus_thread"></div>
        </div>
      </div>
    </article>
    <!-- /.row -->

    <!-- /.row -->
</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
          </div>
        </div>
      </div>
    </footer>

app/views/shared/_header.html.erb
<%= react_component("Header")%>